name: Build Tomcat

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out tomcat-user.xml
        uses: actions/checkout@v3
      
      - name: List project files and java version 
        run: |
          ls -ltr
          java -version
      
      - name: Check out Apache Tomcat
        uses: actions/checkout@v3
        with:
          repository: apache/tomcat # Repository name owner
          ref: master               # The branch, tag or SHA to checkout
          path: ./tomcat            # Relative path under $GITHUB_WORKSPACE
      
      - name: Setup java 9
        uses: actions/setup-java@v1
        with:
          java-version: '9.0.4'    # The JDK version to make available on the path
          java-package: jdk        # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64        # (x64 or X86) - defaults to x64

      - name: List project and java version 
        run: |
          ls -ltr
          java -version
      
      - name: Copy tomcat-users.xml into Tomcat configuration directory
        run: cp -v tomcat-users.xml ./tomcat/conf/tomcat-users.xml   

      - name: Compile Tomcat
        run: |
          cd ./tomcat
          ant